INSERT INTO articles (title, date_published, content)
VALUES 
  ('My Life', now() - '1 days'::INTERVAL, 'Super interesting stuff'),
  ('Wife Try', now() - '1 days'::INTERVAL, 'Super fascinating things'),
  ('My Knife', now() - '2 days'::INTERVAL, 'Super intriguing stings'),
  ('Strife Tie', now() - '2 days'::INTERVAL, 'Uber confronting pings'),
  ('Eye Witness', now() - '2 days'::INTERVAL, 'Funky fresh perspective'),
  ('Fitness Business', now() - '3 days'::INTERVAL, 'Learning the ropes of jump ropes'),
  ('Loch Ness Sighting', now() - '4 days'::INTERVAL, 'Mysterious monsters'),
  ('Fighting Fire', now() - '5 days'::INTERVAL, 'Brave people save lives'),
  ('Tire Trouble', now() - '5 days'::INTERVAL, 'Fix your flat fast'),
  ('Double Duty', now() - '7 days'::INTERVAL, 'Working overtime and under stress'),
  ('Fruity Desserts', now() - '10 days'::INTERVAL, 'Try these tasty treats'),
  ('Desert Lands', now() - '11 days'::INTERVAL, 'Explore the uncharted heat'),
  ('Hands Of Time', now() - '11 days'::INTERVAL, 'Historical findings of yesterday'),
  ('Lime Or Lemon', now() - '11 days'::INTERVAL, 'The great citrus debate'),
  ('Demon Hunting', now() - '12 days'::INTERVAL, 'Real or make believe - you decide'),
  ('Confronting The Truth', now() - '14 days'::INTERVAL, 'Being honest is hard'),
  ('Tooth Hurts', now() - '20 days'::INTERVAL, 'How to prevent tooth decay'),
  ('Shirt Designs', now() - '20 days'::INTERVAL, 'Make a masterful tee'),
  ('Entwined', now() - '21 days'::INTERVAL, 'Roots and history of trees'),
  ('Vine', now() - '22 days'::INTERVAL, 'Roots and history of social media app');